title: "Tanner Josiah Peck - Engineering Portfolio"
description: "Mechanical Engineering Projects, CAD, and Design Work"
theme: null

markdown: kramdown
permalink: pretty

github_username: tannerpeck
linkedin_username: tannerpeck

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

show_header: true
dark_theme: true

kramdown:
  auto_ids: true
  syntax_highlighter: rouge
